#! /bin/bash 

NUM_PARTITION=320
PARTITION_SIZE=1e7

#./../script/install/install_production_ray.sh
#./0.sh $NUM_PARTITION $PARTITION_SIZE
#./1.sh $NUM_PARTITION $PARTITION_SIZE
#./2.sh $NUM_PARTITION $PARTITION_SIZE

./../script/install/install_boa.sh
./d0.sh $NUM_PARTITION $PARTITION_SIZE
./d1.sh $NUM_PARTITION $PARTITION_SIZE
./d2.sh $NUM_PARTITION $PARTITION_SIZE
./b0.sh $NUM_PARTITION $PARTITION_SIZE
./b1.sh $NUM_PARTITION $PARTITION_SIZE
./b2.sh $NUM_PARTITION $PARTITION_SIZE
./e0.sh $NUM_PARTITION $PARTITION_SIZE
./e1.sh $NUM_PARTITION $PARTITION_SIZE
./e2.sh $NUM_PARTITION $PARTITION_SIZE
